# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/Working/Projects/Tutorials/CalculatorLibrary

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv myvenv
            source myvenv/bin/activate
            pip install flake8 pytest pytest-cov
            
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            source myvenv/bin/activate
            pytest -v --cov=calculator
